// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Verifica se DynamoDB e SQS estão acessíveis",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "infra"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/{developer_id}": {
            "get": {
                "description": "Retorna todos os eventos individuais processados para o desenvolvedor informado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Lista eventos de um desenvolvedor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do desenvolvedor",
                        "name": "developer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/aggregator_internal_domain.ProcessedEvent"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/{developer_id}/summary": {
            "get": {
                "description": "Retorna as métricas consolidadas (commits, PRs, tempo médio de review) do desenvolvedor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Resumo agregado de um desenvolvedor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do desenvolvedor",
                        "name": "developer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/aggregator_internal_domain.DeveloperSummary"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "aggregator_internal_domain.DeveloperSummary": {
            "type": "object",
            "properties": {
                "avg_review_time_minutes": {
                    "type": "number"
                },
                "developer_id": {
                    "type": "string"
                },
                "events_processed": {
                    "type": "integer"
                },
                "last_activity": {
                    "type": "string"
                },
                "total_commits": {
                    "type": "integer"
                },
                "total_pull_requests": {
                    "type": "integer"
                }
            }
        },
        "aggregator_internal_domain.ProcessedEvent": {
            "type": "object",
            "properties": {
                "developer_id": {
                    "type": "string"
                },
                "event_id": {
                    "type": "string"
                },
                "metric_type": {
                    "type": "string"
                },
                "processed_at": {
                    "type": "string"
                },
                "processor_id": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Aggregator API",
	Description:      "API de métricas de desenvolvedores — consulta eventos processados e resumos agregados.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
